Simplify check for change of existing migrations (#1465)
* Simplify check for change of existing migrations

* Show full diff in output

diff --git a/.github/workflows/ci-migrations.yml b/.github/workflows/ci-migrations.yml
--- a/.github/workflows/ci-migrations.yml
+++ b/.github/workflows/ci-migrations.yml
@@ -20,11 +20,9 @@ jobs:
       env:
         BASE_SHA: "${{ github.event.pull_request.base.sha }}"
       run: |
-        DIFF="$(git diff "$BASE_SHA" --name-status db/)"
-        printf "%s\n" "$DIFF"
-
-        if [ -n "$DIFF" ] && grep -qPv '^A\b' <<<"$DIFF"; then
-          echo "fatal: migrations cannot be modified or removed, only added."
+        # --diff-filter=a includes all differences except added files.
+        if ! git diff --exit-code --diff-filter=a "$BASE_SHA" ./db; then
+          echo "fatal: migrations cannot be modified or removed, only added"
           exit 1
         fi
     - name: Check validity of migrations
